FROM debian:buster-slim
RUN apt-get update && \
    apt-get install -y gnupg2 wget systemd
RUN wget -O - https://repo.saltstack.com/py3/debian/10/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
RUN echo 'deb http://repo.saltstack.com/py3/debian/10/amd64/latest buster main' > /etc/apt/sources.list.d/saltstack.list
RUN apt-get update && \
    apt-get install -y salt-master salt-ssh salt-api
ENTRYPOINT salt-master --log-level=debug
